name: pbuild
description: Personal build optimized for T480s

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr
      #- etc: /usr/etc

  - from-file: base/fonts.yml

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/zhangyuannie/butter/repo/fedora-%OS_VERSION%/zhangyuannie-butter-fedora-%OS_VERSION%.repo #butter
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo #morewaita
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo #ublue-staging for open-any-terminal, ptyxis, vte291
    install:
      - butter
      - blackbox-terminal
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - fastfetch
      - fish
      - firewall-config
      - gnome-shell-extension-gsconnect
      - ibus-mozc
      - igt-gpu-tools
      - morewaita-icon-theme
      - numix-icon-theme
      - papirus-icon-theme
      - pulseaudio-utils
      - thefuck
      - wl-clipboard
      #from ublue-staging
      - nautilus-open-any-terminal
      #- ptyxis
      #- vte291
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software-rpm-ostree
      - gnome-tour
      - gnome-terminal-nautilus
      - htop
      - nvtop
      - yelp
  
  - from-file: base/t480s.yml
  - from-file: base/gnome-extensions.yml
  - from-file: flatpak/default-flatpaks.yml
  #- from-file: flatpak/yafti.yml

  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service

  - type: signing
