name: pbuild
description: Personal build optimized for T480s

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40
# image-version: latest # for latest stable version, not recommended

modules:
  - type: files
    files:
      # - usr: /usr
      - etc: /etc
      
  - type: rpm-ostree
    repos:
    install:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - fastfetch
      - fish
      - firewall-config
      - gnome-extensions-app
      - igt-gpu-tools
      - make
      - pulseaudio-utils
      - rsms-inter-fonts
      - thefuck
      - wl-clipboard
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software-rpm-ostree
      - gnome-tour
      - yelp
    
  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service
          
  - type: fonts
    nerd-fonts:
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly

  - from-file: btrfs-assistant.yml
  - from-file: btrfs-butter.yml
  - from-file: ptyxis.yml
  - from-file: t480s-utilities.yml
  - from-file: gnome-extensions.yml
  - from-file: flatpak-system.yml
  - from-file: flatpak-user.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
