# image will be published to ghcr.io/<user>/<name>
name: pbuild
# description will be included in the image's metadata
description: Personal build, created out of curiosity

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      # - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
      - etc: /etc # This is for throttled, zcfan, and tlp configs
                  # so they can be further edited without relying on rpm-ostree.

  - type: rpm-ostree
    repos:
      install:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - fastfetch
      - fish
      - firewall-config
      - gnome-boxes
      - gnome-extensions-app
      - igt-gpu-tools
      - make
      - pulseaudio-utils
      - wl-clipboard
      remove:
      - firefox
      - firefox-langpacks
      - gnome-software-rpm-ostree
      - gnome-tour
      - yelp
      
  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service
          
  - type: fonts
    fonts:
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly

  - from-file: btrfs-butter.yml
  - from-file: ptyxis.yml
  - from-file: t480s-utilities.yml
  - from-file: gnome-extensions.yml
  - from-file: flatpak-system.yml
  - from-file: flatpak-user.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
