name: pbuild
description: Personal build optimized for T480s

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc
  
  - from-file: default-packages.yml
  - from-file: t480s-utilities.yml
  - from-file: gnome-extensions.yml
  - from-file: flatpaks.yml
          
  - type: fonts
    fonts:
      # nerd-fonts:
      #   - Terminus
      #   - JetBrainsMono
      #   - NerdFontsSymbolsOnly
      google-fonts:
      　- DotGothic16
        - JetBrains Mono
        - M Plus 1p
        - Nunito Sans
        - Nova Mono
        - PT Sans
        
  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service

  - type: signing
