name: pbuild
description: Personal build optimized for T480s

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc
      
  - type: rpm-ostree
    repos:
    install:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - fastfetch
      - fish
      - gnome-console
      - ibus-mozc
      - firewall-config
      - igt-gpu-tools
      - pulseaudio-utils
      - rsms-inter-fonts
      - thefuck
      - wl-clipboard
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software-rpm-ostree
      - gnome-tour
      - gnome-terminal-nautilus
      - gnome-terminal
      - htop
      - nvtop
      - yelp
    
  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service
          
  - type: fonts
    nerd-fonts:
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly

  - from-file: btrfs-assistant.yml
  - from-file: btrfs-butter.yml
  # - from-file: ptyxis.yml - prefer flatpak ptyxis
  - from-file: t480s-utilities.yml
  - from-file: gnome-extensions.yml
  - from-file: flatpak-system.yml
  # - from-file: flatpak-user.yml
  # - from-file: yafti.yml

  - type: signing
