name: pbuild
description: Personal build optimized for T480s

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc
  
  - from-file: default-packages.yml
          
  # - type: fonts
  #  nerd-fonts:
  #    - Terminus
  #    - JetBrainsMono
  #    - NerdFontsSymbolsOnly
  
  - from-file: t480s-utilities.yml
  
  - from-file: gnome-extensions.yml
  
  - from-file: flatpaks.yml

  # - from-file: yafti.yml | work in progress
  
  - type: systemd
    system:
      disabled:
        - NetworkManager-wait-online.service

  - type: signing
